name: build
on: [push, pull_request]
jobs:
  build_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Compiling
      shell: bash
      run: |
        CL -std:c++17 -utf-8 -O2 -EHsc -Fe:pocketpy src/main.cpp
        mv src/pocketpy.h src/pocketpy.cpp
        CL -std:c++17 -utf-8 -O2 -EHsc -LD -Fe:pocketpy src/pocketpy.cpp
    - uses: actions/upload-artifact@v3
      with:
        name: pocketpy
        path: |
          D:\a\pocketpy\pocketpy\pocketpy.exe
          D:\a\pocketpy\pocketpy\pocketpy.dll
  build_web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mymindstorm/setup-emsdk@v11
    - name: Compiling
      run: |
        bash build_wasm.sh
    - uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: web
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_test_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compiling
      run: |
        bash build_cpp.sh
        python3 scripts/run_tests.py
        ./pocketpy tests/1.py
  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.9'
        channel: 'stable'
    - run: flutter --version
    - name: Compiling
      run: |
        python3 amalgamate.py
        cd plugins/flutter/example
        flutter build apk --split-debug-info=.debug-info --split-per-abi
        cd build/app/outputs/flutter-apk
        mkdir -p output/arm64-v8a
        mkdir -p output/armeabi-v7a
        mkdir -p output/x86_64
        unzip app-arm64-v8a-release.apk -d tmp
        mv tmp/lib/arm64-v8a/libpocketpy.so output/arm64-v8a/libpocketpy.so
        rm -rf tmp
        unzip app-armeabi-v7a-release.apk -d tmp
        mv tmp/lib/armeabi-v7a/libpocketpy.so output/armeabi-v7a/libpocketpy.so
        rm -rf tmp
        unzip app-x86_64-release.apk -d tmp
        mv tmp/lib/x86_64/libpocketpy.so output/x86_64/libpocketpy.so
        rm -rf tmp
    - uses: actions/upload-artifact@v3
      with:
        name: pocketpy
        path: plugins/flutter/example/build/app/outputs/flutter-apk/output