name: website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    ###################################################
    - uses: actions/setup-node@v3.1.1
    - name: Retype build
      run: |
        cd docs
        npm install retypeapp --global
        retype build
    ###################################################
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.25
        actions-cache-folder: 'emsdk-cache'
    - name: Compile
      run: |
        python3 build.py web
        mv web docs/.retype/static
    ###################################################
    - uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: docs/.retype
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
